name: Process Domain Lists

on:
  push:
    branches:
      - main
  workflow_dispatch:       # 手动触发配置
  schedule:
    - cron: '0 * * * *'  # 每小时触发一次

jobs:
  process_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Set Environment Variables
      run: echo "private2=https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/private" >> $GITHUB_ENV

    - name: Download and Process Domain Lists
      run: |
        #!/bin/bash

        # 创建临时文件夹以存放下载的文件
        mkdir -p ./tmp
        mkdir -p ./domains

        # 下载、过滤和处理内容
        curl -sSL ${{private2 }} | \
          grep -v '#' | \                # 过滤掉注释行
          sed '/^\s*$/d' | \              # 过滤掉空行
          sed 's/^full:/DOMAIN:/' | \     # 将行首的 'full:' 替换为 'DOMAIN:'
          sed 's/^/DOMAIN-SUFFIX,/' | \   # 在行首加上 'DOMAIN-SUFFIX,'
          sed 's/^[ \t]*//' | \           # 去除行首的空格或制表符
          > ./tmp/temp-private1.txt        # 将结果保存到临时文件中

        # 输出处理结果
        sort --ignore-case -u ./tmp/temp-private1.txt > ./domains/private1.list

        # 清理临时文件夹
        rm -rf ./tmp

    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v9
      with:
        add: |
          ./domains/private1.list
        message: 'Update domain rules with new data'
